### PR TITLE
fix compiler warnings

### PR DESCRIPTION
**Pull request by tlatorre-uchicago**
This commit fixes a bunch of compiler warnings and maybe 1 bug. The bug was on line 42 of tracking.cc, it appears like the if statement was missing a "{" for the if statement, but maybe I misunderstood?

There are still a few warnings in construction.cc. Basically the whole block:

```c++
if(GeomConfig == 1){
    if(ESRtrue==1){
    G4LogicalBorderSurface *LYSO_Air_Border = new G4LogicalBorderSurface("LYSO_Glue_Border",physLYSO,physWorld,mirrorSurface);
    }
    G4LogicalBorderSurface *Glue_Air_Border1 = new G4LogicalBorderSurface("Glue_Air_Border1",physGlue1,physWorld,groundSurface);
    G4LogicalBorderSurface *Glue_Air_Border2 = new G4LogicalBorderSurface("Glue_Air_Border2",physGlue2,physWorld,groundSurface);
    G4LogicalBorderSurface *Resin_Air_Border1 = new G4LogicalBorderSurface("Glue_Air_Border1",physResin1,physWorld,groundSurface);
    G4LogicalBorderSurface *Resin_Air_Border2 = new G4LogicalBorderSurface("Glue_Air_Border1",physResin2,physWorld,groundSurface);
    G4LogicalBorderSurface *Glue_LYSO_Border1 = new G4LogicalBorderSurface("Glue_LYSO_Border1",physGlue1,physLYSO,groundSurface);
    G4LogicalBorderSurface *Glue_LYSO_Border2 = new G4LogicalBorderSurface("Glue_LYSO_Border2",physGlue2,physLYSO,groundSurface);
    G4LogicalBorderSurface *Glue_Resin_Border1 = new G4LogicalBorderSurface("Glue_LYSO_Border1",physGlue1,physResin1,groundSurface);
    G4LogicalBorderSurface *Glue_Resin_Border2 = new G4LogicalBorderSurface("Glue_LYSO_Border2",physGlue2,physResin2,groundSurface);
}
else if (GeomConfig == 2)
{   
    if(ESRtrue==1){
    G4LogicalBorderSurface *LYSO_Air_Border = new G4LogicalBorderSurface("LYSO_Glue_Border",physLYSO,physWorld,mirrorSurface);
    }
    G4LogicalBorderSurface *Glue_Air_Border1 = new G4LogicalBorderSurface("Glue_Air_Border1",physGlue1,physWorld,groundSurface);
    G4LogicalBorderSurface *Resin_Air_Border1 = new G4LogicalBorderSurface("Glue_Air_Border1",physResin1,physWorld,groundSurface);
    G4LogicalBorderSurface *Glue_LYSO_Border1 = new G4LogicalBorderSurface("Glue_LYSO_Border1",physGlue1,physLYSO,groundSurface);
    G4LogicalBorderSurface *Glue_Resin_Border1 = new G4LogicalBorderSurface("Glue_LYSO_Border1",physGlue1,physResin1,groundSurface);
    
}   
```

The compiler is complaining that none of these are used. I'm not sure I understand the code enough to know if that's correct.

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
Ok, I think I found out that these didn't need to be assigned to variables here (https://geant4-forum.web.cern.ch/t/g4logicalbordersurface/6744), so I removed them. This is I guess potentially a memory leak if the geometry is reinitialized? I also fixed up some of the names which I think were just accidentally copy pasted like:

```c++
    G4LogicalBorderSurface *Resin_Air_Border1 = new G4LogicalBorderSurface("Glue_Air_Border1",physResin1,physWorld,groundSurface);
```

**Comment by grealesguti** [comment]
That was a bug in this version. The loop should only count the photons that are killed, that area needs a little more testing to see if it is working properly, I had some issues and started using the stepping for that. Using the tracking would be more efficient.

**Comment by grealesguti** [comment]
The part it complains about is the section that either introduces the ESR reflective layer or leaves a certain dielectric surface. I can check if it only complains about the latter but the ESR is created. It might be I am not setting anything new with the default definitions.

**Comment by grealesguti** [comment]
The makefile was already changed this morning to include the new class. I did not touch the MakefileTierII though.

**Comment by grealesguti** [comment]
Last comment, I understand that most of the warnings come from unused elements in the code. Most of these were left as they can be useful examples to keep modifying the code or for future modifications I had planned. We should also set a certain regulation to follow for the commit naming  convention. Lets discuss slightly over it tomorrow.

**Comment by grealesguti** [comment]
Thanks for the help!

**Pull request merged**
